### ISSUE TITLE
JavaScript本格入門

### ISSUE THREAD

**Issue by nownabe** [nownabe/engineering-knocks#18]
フロントエンド（ブラウザアプリケーション）プログラミングの基礎を学ぶ

http://www.amazon.co.jp/dp/4774144665

**Comment by risacan** [comment]
- [x] 1、イントロダクション
- [x] 2、基本的な書き方を身につける
- [x] 3、基本データを操作する
- [x] 4、繰り返し利用するコードを一箇所にまとめる
- [x] 5、大規模開発でも通用する書き方を身につける
- [x] 6、ブラウザを自在にあやつる
- [x] 7、HTMLやXMLの文書を操作する
- [ ] 8、サーバ連携でリッチなUIを実装する
- [ ] 9、ライブラリを利用してコードをシンプルにする
- [ ] 10、現場でさけてとおれない応用知識

**Comment by risacan** [comment]
改訂版をやる！
