### ISSUE TITLE
プログラマの数学

### ISSUE THREAD

**Issue by nownabe** [nownabe/engineering-knocks#27]
プログラミングに必要で基本的な数学的知識を学ぶ

http://www.amazon.co.jp/dp/4797329734

**Comment by risacan** [comment]
# 第２章 論理

## 論理積 AかつB

A ∧ B （and）
AとBの両方がtrueの時だけtrue

| A | B | A∧B |
| :-: | :-: | :-: |
| **true** | **true** | **true** |
| true | false | false |
| false | true | false |
| false | false | false |

## 論理和 AまたはB

A ∨ B (or)
AとBの少なくともどちらか片方がtrueのときtrue
AとBの両方がfalseのときだけfalse

| A | B | A∨B |
| :-: | :-: | :-: |
| true | true | true |
| true | false | true |
| false | true | true |
| **false** | **false** | **false** |

## 排他的論理和　AまたはB （でも両方ではない）

A⊕B（exclusive or）
AとBの一方だけがtrueならばtrueになるが、両方がtrueならばfalseになる

| A | B | A⊕B |
| :-: | :-: | :-: |
| true | true | false |
| **true** | **false** | **true** |
| **false** | **true** | **true** |
| false | false | false |

## 等値 AとBは等しい

A = B

| A | B | A=B |
| :-: | :-: | :-: |
| **true** | **true** | **true** |
| true | false | false |
| false | true | false |
| **false** | **false** | **true** |

## 恒真命題

AとBの真偽にかかわらず常にtrueになる命題

## 含意 AならばB

A⇒B

| A | B | A⇒B |
| :-: | :-: | :-: |
| true | true | true |
| **true** | **false** | **false** |
| false | true | true |
| false | false | true |

★前提条件のAがfalseであれば、Bの真偽によらず「AならばB」の値はtrueになる
★
★https://ja.wikipedia.org/wiki/%E8%AB%96%E7%90%86%E5%8C%85%E5%90%AB
左の円がA、右がBだとしたら、色が塗られていない部分は落とし穴だと考える
AがtrueでBがfalseならこの落とし穴にはいってしまうので、A⇒Bはfalse

## 条件付き論理積 &&

A && B
Aという条件によってBを調べるかどうかを判断している

## 条件付き論理和 ||

A || B
AがtrueのときA||Bは必ずtrue,Aがfalseの時A||Bの値はBに等しくなる

# 第３章 剰余

> 直接取り扱うのが難しいような大きな数に直面した時はそこに繰り返し（周期性）を見つけだすことができれば、剰余の力を使って、大きな数をねじ伏せることができる
- パリティ（偶奇）
- パリティ・ビット
- 一筆書きができる⇒すべての頂点が偶点、または、奇点が２個（最初と最後）

**Comment by risacan** [comment]
memoしてないけど最後まで読み終わったので閉じます！
面白かった
